resolver: lts-13.29

packages:
  - co-log-core
  - co-log
  - co-log-polysemy
  - co-log-benchmark

extra-deps:
  - ./submodules/polysemy
  - first-class-families-0.5.0.0
  - th-abstraction-0.3.1.0
  - typerep-map-0.3.2
  - type-errors-0.2.0.0
  - type-errors-pretty-0.0.0.0
  - unagi-chan-0.4.1.0
  - ansi-terminal-0.9.1
  - chronos-1.0.6
  - torsor-0.1
  - aeson-1.4.4.0
  - time-compat-1.9.2.2
